### ISSUE TITLE
DB schema and DDL

### ISSUE THREAD

**Issue by robertyac** [robertyac/FivePoint5#4]
Refine schema and create MySQL DDL for site.

Rough idea: 
<img width="571" alt="Screenshot 2024-02-18 at 6 59 58 PM" src="https://github.com/robertyac/cosc360_proj/assets/112982183/493aede6-4c78-4d44-89db-f2fb51d3bbbb">

**Comment by cmcahoon01** [comment]
https://docs.google.com/document/d/17HzbHTMnGugvAcWQBhsOboaUr3TB7CUUixmTU-CAu98/edit?usp=sharing

**Comment by robertyac** [comment]
DDL has been added to the project files 35941798e72b5b6248a50f675da57f4c8b538b13
